version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_with_volume
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Gắn volume vào thư mục dữ liệu của MySQL

volumes:
  mysql_data:  # Khai báo volume
