version: '3.8'

services:
  react-app:
    build: ./frontend
    container_name: react_build
    volumes:
      - react_build:/app/build

  nginx:
    image: nginx:latest
    container_name: react_nginx
    ports:
      - "8080:80"
    volumes:
      - react_build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react-app

volumes:
  react_build:
